/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import repositorio.RepositorioDados;
import dados.Produto;
import repositorio.RepositorioCliente;
import javafx.scene.control.ComboBox;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import dados.Vendas;
import javax.swing.JList;
import dados.Cliente;
import repositorio.RepositorioVendas;

/**
 *
 * @author alunofavip
 */
public class TelaVendas extends javax.swing.JFrame {
   
    /**
     * Creates new form TelaVendas
     */
    public TelaVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        CampoQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CampoId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoData = new javax.swing.JTextField();
        CampoPagamento = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList();
        CampoCod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Exibir Produtos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade:");

        jLabel2.setText("Seu ID:");

        jLabel3.setText("Data:");

        jLabel4.setText("Forma de pagamento:");

        CampoPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boleto", "Cartão de crédito", "Cartão de débito" }));
        CampoPagamento.setSelectedItem(CampoPagamento);
        CampoPagamento.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                CampoPagamentoComponentAdded(evt);
            }
        });
        CampoPagamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CampoPagamentoItemStateChanged(evt);
            }
        });
        CampoPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoPagamentoMousePressed(evt);
            }
        });
        CampoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPagamentoActionPerformed(evt);
            }
        });

        jButton2.setText("Comprar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(Lista);

        jLabel6.setText("Código do produto desejado:");

        jToggleButton2.setText("Cancelar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoCod, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoId)))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jToggleButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(CampoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CampoCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(CampoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        





// TODO add your handling code here:
        DefaultListModel model1   = new DefaultListModel(); 
        // Produto t = null;
         // DefaultListModel  model2 = new DefaultListModel();
     // DefaultListModel model3 = new DefaultListModel();
        for(Produto p : RepositorioDados.listaProdutos){
           model1.addElement("Produto:  "+ p.getNome() + 
                   "  Descrição:  " 
                   + p.getDesc()+ 
                   "  Preço:  "+
                   p.getPrecoVenda()+ "  Código: " + p.getCodigo());
            
        
        }
        
        Lista.setModel(model1);
       // Lista.setModel(model2);
      // Lista.setModel(model3);

        /* Lista.setModel(new javax.swing.AbstractListModel() {

            @Override
            public int getSize() {
                return RepositorioDados.listaProdutos.size();
            }

            @Override
            public Produto getElementAt(int index) {
                Produto produtos = RepositorioDados.listaProdutos.get(index);
                return produtos;
            }
        });
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CampoPagamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoPagamentoMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CampoPagamentoMousePressed

    private void CampoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPagamentoActionPerformed
        // TODO add your handling code here:
   
     
    
        
    }//GEN-LAST:event_CampoPagamentoActionPerformed

    private void CampoPagamentoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CampoPagamentoComponentAdded
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CampoPagamentoComponentAdded

    private void CampoPagamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CampoPagamentoItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_CampoPagamentoItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           
        int nome = Integer.parseInt(CampoCod.getText());
        
        
        Produto prod = RepositorioDados.pesquisarProdutoPeloCodigo(nome);
        
        if (prod != null){
        
           int opcao = JOptionPane.showConfirmDialog(this,
                    prod.getNome()+ "  "+prod.getDesc(), 
                    "Comprar produto?" ,
                    JOptionPane.YES_NO_OPTION);
            
            
            if (opcao == JOptionPane.YES_OPTION) {
             String Data = CampoData.getText();
      int quantidade = Integer.parseInt(CampoQuantidade.getText());
      int cc = Integer.parseInt(CampoId.getText());
      Cliente cliente = RepositorioCliente.pesquisarClientePeloId(cc);
      //int dd = Integer.parseInt(CampoCod.getText());
     // Produto produ = RepositorioDados.pesquisarProdutoPeloCodigo(dd);
      String pagamento = CampoPagamento.getSelectedItem().toString();
     
      Vendas vendaNova = new Vendas(cliente, prod,Data,quantidade,pagamento);
      RepositorioVendas.adicionarVenda(vendaNova);
      
       int escolha =JOptionPane.showConfirmDialog(this,vendaNova,"Comprar Outro Produto?" ,JOptionPane.YES_NO_OPTION);
       if (escolha ==JOptionPane.YES_OPTION){
       TelaVendas nova = new TelaVendas();
       nova.setVisible(true);
       }else if(escolha == JOptionPane.NO_OPTION) {
                System.out.println(" Não ");
                this.dispose();
            }
            
          
            }else if(opcao == JOptionPane.NO_OPTION) {
                System.out.println(" opcao Não ");
            }else{
            JOptionPane.showMessageDialog(this, "Erro ao efetuar a compra, verifique se a algo de errado");
            }
        
        }
        
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCod;
    private javax.swing.JTextField CampoData;
    private javax.swing.JTextField CampoId;
    private javax.swing.JComboBox CampoPagamento;
    private javax.swing.JTextField CampoQuantidade;
    private javax.swing.JList Lista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
